---
- name: Testing andrewrothstein.ruby
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'ruby --version'
      ansible.builtin.command: ruby --version
      changed_when: false
      register: ruby_test_output
    - name: Output of 'ruby --version'
      ansible.builtin.debug:
        msg: '{{ ruby_test_output.stdout }}'
